const items = [
    {
        id: '001',
        image: '../Pictures/Home Page Banners/tshirt.png',
        company: 'The Souled Store',
        item_name: 'Spiderman: The Web Slinger Men Oversized Sweatshirts',
        original_price: 1999,
        current_price: 1299,
        discount_percentage: 35,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: '../Pictures/Home Page Banners/dupatta.png',
        company: 'Meena Bazaar',
        item_name: 'Printed Art Silk Anarkali Suit Set With Dupatta',
        original_price: 7995,
        current_price: 4638,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: '../Pictures/Home Page Banners/suit.png',
        company: 'Peter England',
        item_name: 'Mens Polyester Blend Suit-Dress Set',
        original_price: 14999,
        current_price: 11249,
        discount_percentage: 25,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: '../Pictures/Home Page Banners/topp.png',
        company: 'Symbol Premium',
        item_name: 'Womens Crop Top',
        original_price: 1499,
        current_price: 799,
        discount_percentage: 47,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: '../Pictures/Home Page Banners/shirtt.png',
        company: 'Allen Solly',
        item_name: 'Mens Regular Fit Polo',
        original_price: 1099,
        current_price: 699,
        discount_percentage: 36,        
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: '../Pictures/Home Page Banners/jacket.png',
        company: 'Levis',
        item_name: 'Womens Jacket',
        original_price: 4999,
        current_price: 2249,
        discount_percentage: 55,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: '../Pictures/Home Page Banners/top.png',
        company: 'The Indian Garage Co',
        item_name: 'Womens Floral Printed Cotton Top',
        original_price: 1599,
        current_price: 469,
        discount_percentage: 71,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: '../Pictures/Home Page Banners/saree.png',
        company: 'AKHILAM',
        item_name: 'Womens Georgette Banarasi Silk Saree with Unstitched Blouse Piece',
        original_price: 7649,
        current_price: 1699,
        discount_percentage: 78,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '009',
        image: '../Pictures/Home Page Banners/nehru.png',
        company: 'Jompers',
        item_name: 'Mens Woven Design Nehru Jacket',
        original_price: 2499,
        current_price: 890,
        discount_percentage: 64,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '010',
        image: '../Pictures/Home Page Banners/poloo.png',
        company: 'Allen Solly',
        item_name: 'Mens Regular Fit Polo',
        original_price: 1099,
        current_price: 699,
        discount_percentage: 36,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '011',
        image: '../Pictures/Home Page Banners/silksaree.png',
        company: 'Varkala Silk Sarees',
        item_name: 'Women Paithani Soft Silk Kadiyal Maharani Saree With Blouse Piece',
        original_price: 11199,
        current_price: 2639,
        discount_percentage: 76,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '012',
        image: '../Pictures/Home Page Banners/floral.png',
        company: 'Leriya Fashion',
        item_name: 'Tropical Leaf Printed Rayon Shirts for Men ',
        original_price: 1999,
        current_price: 289,
        discount_percentage: 86,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];